name: Trigger auto deployment for container-app-oh2sc4p2eyugg

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-oh2sc4p2eyugg-AutoDeployTrigger-b958fd3d-2868-4d06-8096-0baeec076d86.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPOH2SC4P2EYUGG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPOH2SC4P2EYUGG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPOH2SC4P2EYUGG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryoh2sc4p2eyugg.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPOH2SC4P2EYUGG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPOH2SC4P2EYUGG_REGISTRY_PASSWORD }}
          containerAppName: container-app-oh2sc4p2eyugg
          resourceGroup: MaryamACA01
          imageToBuild: containerregistryoh2sc4p2eyugg.azurecr.io/container-app-oh2sc4p2eyugg:${{ github.sha }}
          


